Feature/homework 1
Systems-Development-and-Frameworks/TheCodeNinjas pull request #2
Opened 2020-10-22 11:47 UTC by s0557917

Pull request for homework one using TypeScript, Vue3 with the compositionAPI and a very fancy design.

2020-10-26 18:30 UTC, roschaefer requested changes
![scrutiny](https://media.giphy.com/media/42wQXwITfQbDGKqUP7/giphy.gif)

This looks really fancy! And you used the new composition API of Vue 3, nice. Did somebody of you want to give a lightning talk about the new composition API?

:x: Unfortunately I found one missed objective:
> :star: The items are always ordered by votes in descending order
> - You could use computed properties for the list of ordered items


![Screenshot - 2020-10-26T190716 337](https://user-images.githubusercontent.com/2110676/97212991-637a0480-17c1-11eb-8dac-e927b24d0a7e.png)


![Screenshot - 2020-10-26T190821 957](https://user-images.githubusercontent.com/2110676/97213028-6e349980-17c1-11eb-885a-6c97783ed021.png)


This is a nice example how state can lead to errors. Try to avoid state as much as you can. If you have the opportunity to let the framework update the state, use it.

So you achieved 9/10 :star: in this submission. Congrats!

2020-10-26 18:30 UTC, roschaefer commented on README.md
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
![wtf](https://media.giphy.com/media/69rOKW0lSeWSxYiS2O/giphy.gif)

2020-10-26 18:30 UTC, roschaefer commented on README.md
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
You should link to the installation instructions instead.

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsItem.vue
> +      context.emit("upvote", newsItem.value.id);
```suggestion
      context.emit("update", {...newsItem, votes: (newsItem.votes + 1)});
```
This way, the parent component knows the least about it's child components.

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsList.vue
> +        <tbody v-if="newsItems.length > 0">
```suggestion
        <tbody v-if="newsItems.length">
```
I know it's ugly, but in JavaScript, zero `0` evaluates to `false`.

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsList.vue
> +            @downvote="downvoteNewsItem"
The interface here could be smaller if you would re-use events :point_up:

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsList.vue
> +              No News in the list!
How do you know, this is a task of exercise `#2`. :astonished:

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsList.vue
> +            type="text"
```suggestion
```
I believe, that's the default.

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsList.vue
> +        .sort((a, b) => b.votes - a.votes);
You can [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) this with a computed property `sortedNewsItems`. See: https://vuejs.org/v2/guide/computed.html

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsList.vue
> +          }
Prefer guard-clause:
```suggestion
          if (item.id !== id) return item
          return new NewsItemModel({
            ...item,
            votes: item.votes - 1
          }); 
```
See: https://dev.to/wagslane/guard-clauses-how-to-clean-up-conditionals-2fdm

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsList.vue
> +      newsTitle.value = "";
I would suggest to use a dedicated component for the `<form>` which takes this responsibility and `$emits` the created `newsItem`.

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsList.vue
> +<style scoped lang="scss"></style>
```suggestion
```

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/components/NewsList.vue
> +      newsItems.value = newsItems.value.filter(item => item.id != id);
```suggestion
      newsItems.value = newsItems.value.filter(item => item.id !== id);
```
Because `5 != '5'` returns `false` in JavaScript :crying_cat_face:

2020-10-26 18:30 UTC, roschaefer commented on homeworks/homework-1/src/models/news-item.model.ts
> +}
```suggestion
  compareTo(other: NewsItemModel) : Number {
    return other.votes - this.votes
  }
}
```

Then you can later do:
```js
.sort((a, b) => a.compareTo(b));
```

Just an idea :wink:

2020-10-28 14:14 UTC, s0557917 commented
Most issues were fixed in a new commit, with exception of the dedicated component for the form. This issue will be improved later, so that the new changes from the "homework" repository can be merged.

2020-10-28 14:15 UTC, merged