Feature/homework 2
Systems-Development-and-Frameworks/TheCodeNinjas pull request #3
Opened 2020-11-04 14:40 UTC by FlorianTh2

We have added some tests. Please review out current state.

2020-11-09 16:25 UTC, roschaefer requested changes
![right on time](https://media.giphy.com/media/l1J9MTa7XfOCix5iU/giphy.gif)

~Your `NewsList.stories.js` is empty`~

~There is a reason why I asked for every component: If you had `a11y` configured, then I'm pretty sure that your `NewsList` wouldn't pass all accessibility tests, because it renders the `<form>` element.~

You guys are **just in time** with 9a6843c0b1394882861a981e9e09b3535572103a - otherwise I would have given you 7/10 :star: instead of 9/10. The only missing star (and you have time for that until Wednesday) is to give a review to another group. I can not see a review given by a member of this group in my email notificaitons.

Apart from that, this is a really sold, very clean and very concise PR. You only seem to have some troubles with the wording of your test case descriptions.

E.g. check the command line output of `jest`:
```
 PASS  src/components/NewsList/NewsList.spec.ts
  NewsList
    ✓ check App-instance-existance and newsList-instance-existance (25ms)
    ✓ check if renders news item for each item in list if list empty (6ms)
    ✓ check if renders news item for each item in list if list empty and filled again (13ms)
    ✓ renders empty list message (7ms)
    ✓ check order: check initial order before clicking the toggle-button (24ms)
    ✓ toggles between ascending and descending order (18ms)
````
and make sure that the text reads nicely and documents the behaviour well.

2020-11-09 16:25 UTC, roschaefer commented on .github/workflows/DeployActions.yml
> +    - run: npm run lint --fix
```suggestion
    - run: npm run lint
```
Or do you want your CI server to contribute to your code? :stuck_out_tongue:

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/.storybook/main.js
> +    "@storybook/addon-essentials"
Where is `@storybook/addon-a11y`?

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.spec.ts
> +  it("check App-instance-existance and newsList-instance-existance", () => {
Be affirmative in your test case descriptions.
```suggestion
  it("exists", () => {
```

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.spec.ts
> +    expect(wrapper.findAllComponents(NewsItem).length).toBe(0);
```suggestion
    expect(wrapper.findAllComponents(NewsItem)).toHaveLength(0);
```

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.spec.ts
> +      }
```suggestion
      propsData: {
        initialItems: []
      }
```
Don't set internal state. Instead, introduce a property `initialItems` on the `NewsList` component.

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.spec.ts
> +  it("check if renders news item for each item in list if list empty", () => {
```suggestion
  it("renders no NewsItem", () => {
```
Huh? I thought it's empty.

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.spec.ts
> +  it("check if renders news item for each item in list if list empty and filled again", () => {
```suggestion
  it("renders a NewsItem for each item in the list", () => {
```
What are you trying to say?

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.spec.ts
> +  it("renders empty list message", () => {
```suggestion
  it("renders empty state", () => {
```
"Emty state" seems to be a vocable: https://material.io/design/communication/empty-states.html#content

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.spec.ts
> +  it("check order: check initial order before clicking the toggle-button", async () => {
```suggestion
  it("orders in descending order by default", async () => {
```

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.spec.ts
> +  it("toggles between ascending and descending order", async () => {
Good :+1:

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.vue
> +          votes: newsItem.votes
This limits the re-use of that `updateNewsItem` handler but it looks intentional. What's your motivation to restrict updates to `votes` property only? :thinking: 

If you wouldn't to that, you could reuse that handler for any other component which emits an updated item.

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/components/NewsList/NewsList.vue
> +        title: this.newsTitle,
I still prefer to put the form into a dedicated component - but your choice! :stuck_out_tongue:

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/models/news-item.model.ts
> +    return other.votes - this.votes;
```suggestion
    return (-1) * this.compareToAscending(other)
```
:thinking: maybe? Or just keep your code, this idea is actually a little less obvious...

2020-11-09 16:25 UTC, roschaefer commented on homeworks/homework-vue/src/stories/Button.stories.js
> +};
```suggestion
```
Please remove unrelated changes!

2020-11-10 10:12 UTC, KarakoA approved these changes
Pretty solid, good job!

2020-11-10 10:12 UTC, KarakoA commented on homeworks/homework-vue/.storybook/preview.js
> +  actions: { argTypesRegex: "^on[A-Z].*" },
Used to automatically map events starting with `on` e.g. `onUpdate` to actions in storybook. Could be removed since not used

2020-11-10 10:12 UTC, KarakoA commented on homeworks/homework-vue/src/App.vue
> +export default Vue.extend({
Why `Vue.extend`? because of typescript?

2020-11-11 14:55 UTC, merged

2020-11-12 11:34 UTC, roschaefer commented
I saw your code review here: https://github.com/Systems-Development-and-Frameworks/SudoKings/pull/3#pullrequestreview-527466464 that was the missing :star: 

Well done! I added 10/10 :star: for this submission!