Feature/homework 5
Systems-Development-and-Frameworks/TheCodeNinjas pull request #8
Opened 2020-12-10 11:13 UTC by s0557917

-Implementation of homework 5

2021-01-08 09:55 UTC, Marcelloloco approved these changes
Good job! 

You also requested a review, so there's another :+1:

2021-01-08 09:55 UTC, Marcelloloco commented on backend/README.md
> +We also chose it, as it was an interesting API and we wanted to learn how to work with it.
Motivation objective done! :+1:

2021-01-08 09:55 UTC, Marcelloloco commented on backend/README.md
> +## Installation
Installation manual objective done! :+1:

2021-01-08 09:55 UTC, Marcelloloco commented on backend/.env.example
> +GRAPH_CMS_API_TOKEN=
No API key committed. :+1:

2021-01-08 09:55 UTC, Marcelloloco commented on backend/src/create-permissions.ts
> +  return shield(
Permissions handled for calling mutations and queries. :+1:

2021-01-08 09:55 UTC, Marcelloloco commented on backend/src/create-resolvers.ts
> +    Person: personsProperties(subSchemas, executor),
Resolvers delegation for persistent communication with Database :+1:

2021-01-08 09:55 UTC, Marcelloloco commented on backend/src/resolvers/persons.resolver.spec.ts
> +});
Tests adjusted and are running fine on Github actions :+1:

2021-01-12 11:40 UTC, medizinmensch requested changes
Hi Team!

Thanks for your submission!
Your code looks code, even though it's a bit excessive (you have more than twice as many changed files as other groups), but I guess this is because you make use of TypeScript features like interfaces.

The tests run through and also successfully fail if I change the `expected` values. 👍 

Sadly, the server itself wont start for me. I get this error:

```
$ npm run start
> backend@1.0.0 start /home/youri/dev/uni/sdaf/groups/TheCodeNinjas/backend
> ts-node src/index.ts



Error: It seems like you have applied rules to Query.persons fields but Shield cannot find them in your schema.
    at applyRuleToType (/home/youri/dev/uni/sdaf/groups/TheCodeNinjas/backend/node_modules/graphql-shield/src/generator.ts:151:13)
    at /home/youri/dev/uni/sdaf/groups/TheCodeNinjas/backend/node_modules/graphql-shield/src/generator.ts:265:25
    at Array.reduce (<anonymous>)
    at generateMiddlewareFromSchemaAndRuleTree (/home/youri/dev/uni/sdaf/groups/TheCodeNinjas/backend/node_modules/graphql-shield/src/generator.ts:259:8)
    at MiddlewareGenerator.generator (/home/youri/dev/uni/sdaf/groups/TheCodeNinjas/backend/node_modules/graphql-shield/src/generator.ts:293:5)
    at MiddlewareGenerator.generate (/home/youri/dev/uni/sdaf/groups/TheCodeNinjas/backend/node_modules/graphql-middleware/src/generator.ts:19:17)
    at /home/youri/dev/uni/sdaf/groups/TheCodeNinjas/backend/node_modules/graphql-middleware/src/middleware.ts:72:25
    at Array.map (<anonymous>)
    at applyMiddlewareWithOptions (/home/youri/dev/uni/sdaf/groups/TheCodeNinjas/backend/node_modules/graphql-middleware/src/middleware.ts:70:45)
    at Object.applyMiddleware (/home/youri/dev/uni/sdaf/groups/TheCodeNinjas/backend/node_modules/graphql-middleware/src/middleware.ts:129:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@1.0.0 start: `ts-node src/index.ts`
npm ERR! Exit status 1
```

I could not quickly make out the issue. I'm on the `/feature/homework-5` branch, pulled properly and didn't change any files (except the `.env`). I added one line with `console.log(fetchResult.json()` to `create-graph-cms-schema.ts`/`executor` to confirm a working connection and it looks like my GraphCMS settings are correct. My GraphCMS Schema also looks like yours:

<img width="1075" alt="Photoshop_5EC5JRKmuI" src="https://user-images.githubusercontent.com/26927853/104309261-283ec600-54d2-11eb-90d6-934ca4adf783.png">


I don't know what the issue is. Do you guys have any idea?

Below, you'll find a comment on why I have to deduct one :star:. 

So far, you get 7/10 :star: for the following:


:star: For choosing a scenario   and writing installation instructions in README.md.
:star:   For explaining WHY you have chosen the scenario in the README.md.
:star: For not committing   sensitive secrets (e.g. API keys) unencrypted to the repository.
:star: :star: Your software   tests are free of side effects.
:star:   Your database is never left in an invalid state.
:star: You deny the client to   call mutations and queries of your subschema directly.
:star:   For requesting a review and reviewing another team's PR.

If we get the code running and find out it was my fault, I can also give you 

> :star:   :star: Data created in mutations are persisted and your queries and mutations   still work as expected.

Youri

2021-01-12 11:40 UTC, medizinmensch commented on backend/src/create-permissions.ts
> +      fallbackRule: allow,
Here, as well as in line 55 and 73, you set your fallback rule as "allow". This default gives access to all further mutations and queries, especially to the ones in your subschema. This means you're getting an :x: here:

:star: You deny the client to   call mutations and queries of your subschema directly.

2021-01-12 14:50 UTC, s0557917 commented on backend/src/create-permissions.ts
> +      fallbackRule: allow,
Hey Youri, for some reason I can only reply to this comment and not the whole PR Review. Saddly the secret in the Readme was left there by accident, we removed everything but somehow we oversaw it. I removed it so it`s no longer there. 
Regarding the server not starting: I could not reproduce the error you are getting. I cloned the project and added our values to the .env file in the backend folder and it works. Your GraphCMS schema also looks correct so I am not sure where the error happens.

2021-01-13 18:02 UTC, medizinmensch approved these changes
We talked today, I will re-review your code tomorrow. Until then, you can already merge :)

2021-01-13 18:20 UTC, merged